export const DASHBOARD = '/'
export const LOGIN = '/login'
export const SIGN_UP = '/signup'
export const NOT_FOUND = '/signup'
export const PROFILE = '/p/:username'
export const LOGNOT_FOUNDIN = '/not-found'